[project]
name = "taxifare-mlops-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andreas Grabowski", email = "andreas@a-grabowski.de" }
]
requires-python = ">=3.12.9"
dependencies = [
    "fastapi>=0.141.1",
    "pandas<3",
    "uvicorn>=0.52.4",
    "db-dtypes>=1.7.1",
    "google-cloud-bigquery>=3.44.0",
    "matplotlib>=3.11.1",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
taxifare-mlops-intro = "taxifare_mlops_intro:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
